# Generated by Django 5.0.1 on 2024-01-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image_url', models.URLField(default='')),
                ('description', models.TextField()),
                ('github_url', models.URLField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='post_image_url',
            field=models.URLField(default=''),
        ),
    ]
